package pro.inmost.android.visario.data.api.services.auth

import kotlinx.coroutines.Dispatchers.IO
import kotlinx.coroutines.withContext
import pro.inmost.android.visario.data.api.ChimeApi.Companion.STATUS_OK
import pro.inmost.android.visario.data.api.dto.requests.auth.FacebookLoginRequest
import pro.inmost.android.visario.data.api.dto.requests.auth.GoogleLoginRequest
import pro.inmost.android.visario.data.api.dto.requests.auth.LoginRequest
import pro.inmost.android.visario.data.api.dto.requests.auth.RegistrationRequest
import pro.inmost.android.visario.data.api.dto.responses.auth.AuthResponse
import pro.inmost.android.visario.utils.logE


/**
 * User authenticator
 *
 * @property service - authentication service generated by retrofit
 *
 */
class Authenticator(private val service: AuthService) {

    suspend fun login(email: String, password: String): Result<AuthResponse> = withContext(IO) {
        kotlin.runCatching {
            val response = service.login(LoginRequest(email, password))
            if (response.status == STATUS_OK) {
                Result.success(response)
            } else {
                logE("login error: ${response.message}")
                Result.failure(Throwable(response.message))
            }
        }.getOrElse {
            logE("login error: ${it.message}")
            Result.failure(Throwable(it))
        }
    }

    suspend fun loginViaFacebook(token: String): Result<AuthResponse> = withContext(IO) {
        kotlin.runCatching {
            val response = service.loginViaFacebook(FacebookLoginRequest(token))
            if (response.status == STATUS_OK) {
                Result.success(response)
            } else {
                logE("login error: ${response.message}")
                Result.failure(Throwable(response.message))
            }
        }.getOrElse {
            logE("login error: ${it.message}")
            Result.failure(Throwable(it))
        }
    }

    suspend fun loginViaGoogle(token: String): Result<AuthResponse> = withContext(IO) {
        kotlin.runCatching {
            val response = service.loginViaGoogle(GoogleLoginRequest(token))
            if (response.status == STATUS_OK) {
                Result.success(response)
            } else {
                logE("login error: ${response.message}")
                Result.failure(Throwable(response.message))
            }
        }.getOrElse {
            logE("login error: ${it.message}")
            Result.failure(Throwable(it))
        }
    }

    suspend fun forgotPassword(email: String) = withContext(IO){
        kotlin.runCatching {
            val response = service.forgotPassword(email)
            if (response.equals("ok", true)){
                Result.success(Unit)
            } else {
                Result.failure(Throwable("Forgot password request failed"))
            }
        }.getOrElse {
            logE("forgot password error: ${it.message}")
            Result.failure(Throwable(it))
        }
    }

    fun logout(): Boolean {
        clearTokens()
        return true
    }

    suspend fun register(body: RegistrationRequest): Result<Unit> = withContext(IO){
        kotlin.runCatching {
            val response = service.register(body)
            if (response.status == STATUS_OK) {
                Result.success(Unit)
            } else {
                logE("register error: ${response.message}")
                Result.failure(Throwable(response.message))
            }
        }.getOrElse {
            logE("register error: ${it.message}")
            Result.failure(Throwable(it))
        }
    }


    /**
     * Store actual tokens in RAM
     *
     */
    fun saveTokens(accessToken: String, refreshToken: String) {
        TokensHolder.accessToken = accessToken
        TokensHolder.refreshToken = refreshToken
    }

    /**
     * Delete tokens from RAM
     *
     */
    fun clearTokens(){
        TokensHolder.accessToken = ""
        TokensHolder.refreshToken = ""
    }

    object TokensHolder{
        var accessToken: String = ""
        var refreshToken: String = ""
    }
}